insert into public.publishing_accounts (
  platform,
  account_name,
  handle,
  account_url,
  ownership_type,
  partner_name,
  active,
  notes
)
values
  ('INSTAGRAM', 'ai.excel', '@ai.excel', 'https://www.instagram.com/ai.excel/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'ai.tech.moments', '@ai.tech.moments', 'https://www.instagram.com/ai.tech.moments/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'aigleeson', '@aigleeson', 'https://www.instagram.com/aigleeson/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'ainterestingaf', '@ainterestingaf', 'https://www.instagram.com/ainterestingaf/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'ainterestingupdate', '@ainterestingupdate', 'https://www.instagram.com/ainterestingupdate/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'artificialmente.ia', '@artificialmente.ia', 'https://www.instagram.com/artificialmente.ia/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'artificialntellligence', '@artificialntellligence', 'https://www.instagram.com/artificialntellligence/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'bballclan', '@bballclan', 'https://www.instagram.com/bballclan/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'beatprocrastinationnow', '@beatprocrastinationnow', 'https://www.instagram.com/beatprocrastinationnow/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'chatgptips', '@chatgptips', 'https://www.instagram.com/chatgptips/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'chatgptricks', '@chatgptricks', 'https://www.instagram.com/chatgptricks/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'chatgptruco', '@chatgptruco', 'https://www.instagram.com/chatgptruco/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'costarica', '@costarica', 'https://www.instagram.com/costarica/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'em3rging', '@em3rging', 'https://www.instagram.com/em3rging/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'estoicomorir', '@estoicomorir', 'https://www.instagram.com/estoicomorir/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'estoicovivir', '@estoicovivir', 'https://www.instagram.com/estoicovivir/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'ivanelgrande', '@ivanelgrande', 'https://www.instagram.com/ivanelgrande/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'louisgson', '@louisgson', 'https://www.instagram.com/louisgson/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'planet.ai_', '@planet.ai_', 'https://www.instagram.com/planet.ai_/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'programming__india', '@programming__india', 'https://www.instagram.com/programming__india/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'sentientagency', '@sentientagency', 'https://www.instagram.com/sentientagency/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'sergioprompts', '@sergioprompts', 'https://www.instagram.com/sergioprompts/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'stoicreflections', '@stoicreflections', 'https://www.instagram.com/stoicreflections/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'tecnologia', '@tecnologia', 'https://www.instagram.com/tecnologia/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'traselveloreal', '@traselveloreal', 'https://www.instagram.com/traselveloreal/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'trends', '@trends', 'https://www.instagram.com/trends/', 'SENTIENT_OWNED', null, true, 'Sentient Network internal Instagram account.'),
  ('INSTAGRAM', 'aitrendz.xyz', '@aitrendz.xyz', 'https://www.instagram.com/aitrendz.xyz/', 'EXTERNAL_PARTNER', 'Sentient partner network', true, 'Sentient Network partner Instagram account.'),
  ('INSTAGRAM', 'blueviper.ai', '@blueviper.ai', 'https://www.instagram.com/blueviper.ai/', 'EXTERNAL_PARTNER', 'Sentient partner network', true, 'Sentient Network partner Instagram account.'),
  ('INSTAGRAM', 'mindset.therapy', '@mindset.therapy', 'https://www.instagram.com/mindset.therapy/', 'EXTERNAL_PARTNER', 'Sentient partner network', true, 'Sentient Network partner Instagram account.'),
  ('INSTAGRAM', 'theaipage', '@theaipage', 'https://www.instagram.com/theaipage/', 'EXTERNAL_PARTNER', 'Sentient partner network', true, 'Sentient Network partner Instagram account.'),
  ('INSTAGRAM', 'theartificialintelligence', '@theartificialintelligence', 'https://www.instagram.com/theartificialintelligence/', 'EXTERNAL_PARTNER', 'Sentient partner network', true, 'Sentient Network partner Instagram account.')
on conflict (account_url) do update
set
  platform = excluded.platform,
  account_name = excluded.account_name,
  handle = excluded.handle,
  ownership_type = excluded.ownership_type,
  partner_name = excluded.partner_name,
  active = excluded.active,
  notes = excluded.notes;
